Lambda-School-Labs/CS10-car-reviews

car-reviews/package.json, car-reviews/src/App.js, car-reviews/src/components/MainPage/searchbar.css, car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/index.js, car-reviews/yarn.lock
I created a very rough version of the Searchbar with Reactstrap, with hardcoded placeholders that emulate the real for the dropdowns. It includes borders that will be removed later. I rendered it directly into App for now, but later will move it into the "MainPage" component(it hasn't been made yet).
- [X ] New feature (non-breaking change which adds functionality)
I yarn started my app and checked it in real time, since what i am doing is at the moment, purely visual. I put in colored borders to be explicit about what divs I was working in. I had some bugs with the "dropdown" reactstrap component, but fixed it by using the "uncontrolled dropdown" component.
=> WIP on Searchbar

car-reviews/package.json, car-reviews/public/index.html, car-reviews/src/App.css, car-reviews/src/App.js, car-reviews/src/components/UserPage/billing.js, car-reviews/yarn.lock
Added in stripe by using react-stripe-elements
had to add in to the index.html, app.js, and billing.js
created and addded in billing.js and  UserPage Folder
verified that elements showed up on local machine.
=>  Added in Stripe and built out the billing component

car-reviews/.eslintrc.json, car-reviews/.prettierrc, car-reviews/package.json, car-reviews/src/components/UserPage/header.css, car-reviews/src/components/UserPage/header.js, car-reviews/src/components/UserPage/leftnavbar.css, car-reviews/src/components/UserPage/leftnavbar.js, car-reviews/src/components/UserPage/settings.js, car-reviews/yarn.lock
- Added Left Nav Bar and Header components for the UserPage.
- [x ] New feature (non-breaking change which adds functionality)
- Was tested on localhost to be sure that everything rendered properly.
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] I have added …
=> User left navigation branch

car-reviews/src/App.js, car-reviews/src/components/MainPage/MainPage.js, car-reviews/src/components/MainPage/maincontent.js, car-reviews/src/components/MainPage/mainpage.css, car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/UserPage/UserPage.js
Adds placeholders for the main content of the landing page.
Reorganizes the Component structure.
Adds About The Team link to the bottom of the main page.
Has minimal styling to keep the Buttons approximately the size they need to be.
I have had Chrome open to check the how the app renders in real-time.
=> Main Page-Main Content (pagesbranch)

backend/src/models/UserModel.js
This PR just adds a missing comma
=> fixed missing comma in UserModel.js

car-reviews/src/components/MainPage/MainPage.js, car-reviews/src/components/MainPage/maincontent.js, car-reviews/src/components/MainPage/mainpage.css, car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/MainPage/searchresults.js
-Adds Search Result Component with hardcoded placeholders.
-Adds comments under imports to each component file that explain that file's purpose, and also where it is being rendered.
-Cleans up the main page css file.
I rendered in my browser and looked at in real-time. To better emulate what the final product would look like, I commented out <MainContent /> on line 15 in MainPage.js.
=> Search Results Component

backend/src/models/CarModel.js, backend/src/models/ReviewModel.js, backend/src/routers/authRouter.js, backend/src/routers/content/popularRouter.js, backend/src/routers/content/reviewsRouter.js, backend/src/routers/contentRouter.js
Basic router implementation for the main page: Endpoints for featured reviews, popular cars, and popular reviewers. Also POST endpoint for new review, and additions to Mongo Schema for sorting purposes.
=> Main Page endpoints implementation

car-reviews/src/components/UserPage/billing.css, car-reviews/src/components/UserPage/userpage.css
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Updated Css for billing and re-arranged how billing is displayed

car-reviews/src/components/UserPage/UserPage.js, car-reviews/src/components/UserPage/reviewmodal.js
-Created a basic review modal with placeholder data. For production, there will be much more going on. 
I rendered it in-browser in real-time as I built it.
=> created placeholder review modal

car-reviews/src/components/UserPage/header.js, car-reviews/src/components/UserPage/myreviews.js, car-reviews/src/components/UserPage/reviewlist.css, car-reviews/src/components/UserPage/reviewlist.js, car-reviews/src/components/UserPage/settings.js, car-reviews/src/components/UserPage/usersettings.js, car-reviews/src/data.js
Display My Reviews view for user when they have no and multiple reviews.
- Added a data.js file as dummy data for listing review info on cards.
- The user section currently in made dynamic by passing it down as props to <Header/>
- reviewslist.js will display two diff views depending on reviews.length
- <MyReviews/> component complete and can now be routed to.
- Loading the page in the browser by placing <MyReviews/> (and commenting out everything else) inside UserPage.js and just commenting out <MainPage/> in App.js
=> Display My Reviews view for user when they have no and multiple reviews.

backend/README.md, backend/package.json, backend/src/models/CarModel.js, backend/src/models/ReviewModel.js, backend/src/models/UserModel.js, backend/src/routers/authRouter.js, backend/src/routers/content/popularRouter.js, backend/src/routers/content/reviewsRouter.js, backend/src/routers/content/userRouter.js, backend/src/server.js, backend/src/tests/model_tests/car_model_tests.js, backend/src/tests/model_tests/model_tests_helper.js, backend/src/tests/model_tests/relational_test.js, backend/src/tests/model_tests/review_model_tests.js, backend/src/tests/model_tests/user_model_tests.js, backend/src/tests/routing_tests/auth_router_tests.js, backend/src/tests/routing_tests/content_router_tests.js, backend/src/tests/routing_tests/popular_router_tests.js, backend/src/tests/routing_tests/reviews_router_tests.js, backend/src/tests/routing_tests/routing_tests_helper.js, backend/src/tests/routing_tests/user_router_tests.js, backend/yarn.lock
Unit Testing for all routes and for the database is complete.
Tests now run with the commands:
- 'yarn test_db'
- 'yarn test_routing'
Fixes # Minor
- changed the only endpoint in the userRouter to a GET
Adding content
Tests were all ran with Mocha and Nodemon--all are passing
=> Finished Testing

car-reviews/src/App.js, car-reviews/src/components/MainPage/MainPage.js, car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/UserPage/UserPage.js
Altered the routes to resemble the app better. created some link items for moving between Search and main page
testing routing and link on local machine 
=>  Created routing for Searchpage and mainpage and re-organized.

car-reviews/FE-Readme.md
- Created an initial readme that lists the technologies we use
- Gives explanations of the different components that are used and where they are used.
- Leaves a section for endpoints to be updated once those are written.
Just need someone to go over it and make sure it's all good, for now. It will need more information once the code is there for it.
=> initial readme

backend/src/routers/content/reviewsRouter.js, backend/src/routers/routing_middleware/checkIfCar.js, backend/src/routers/routing_middleware/verifyJWTMiddleware.js
Add functionality to reviews POST route to update multiple documents. Add middlware to check if car exists when creating review. Add search endpoint.
=> Reviews and search backend

car-reviews/src/App.js, car-reviews/src/components/MainPage/LoginRegister.css, car-reviews/src/components/MainPage/loginRegister.js
Pair programmed with Charlie and got the Login and Register page done and some styling done on it as well. 
Tested on local machine using local host
=>  Created and did some styling on register/login page

backend/src/server.js
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> correct mongodb env var

backend/package.json, backend/src/server.js
This is the version of the backend that was deployed on 9/13. It has full functionality to interact with the Heroku and mLab hosting.
=> Deployed backend

car-reviews/src/App.js, car-reviews/src/components/MainPage/MainPage.js, car-reviews/src/components/UserPage/UserPage.js, car-reviews/src/components/UserPage/leftnavbar.js, car-reviews/src/components/UserPage/reviewlist.js
- Imports removed from MainPage.js, UserPage.js, & reviewlist.js
- Links to Billing and Settings in LeftNav changed to reflect App.js
Went to each route in App.js to ensure that the components were rendering properly. Clicked on the tabs on LeftNav to ensure they were going to the appropriate links.
=> Removed imports in files that were not being used. Minor tweaks.

car-reviews/src/components/MainPage/loginRegister.js
Updated to redirect for login if user is logged in
tested on local machine with me and charlie
=>  Updated register and login to redirect safely to main page after login.

backend/package.json, backend/src/models/CarModel.js, backend/src/models/ReviewModel.js, backend/src/models/UserModel.js, backend/src/routers/content/popularRouter.js, backend/src/routers/content/reviewsRouter.js, backend/src/routers/content/userRouter.js, backend/src/routers/paymentRouter.js, backend/src/routers/routing_middleware/checkIfCar.js, backend/src/server.js, backend/yarn.lock
Add payment router for Stripe payment processing. Add paid field to UserModel to keep track of paid vs unpiad users. Add Average Score calculation for car model. Add route to edit and retrieve single review. Add lastUpdated field for reviews.
=> Stripe implementation - backend

car-reviews/package.json, car-reviews/src/components/MainPage/hamburgerMenu.css, car-reviews/src/components/MainPage/hamburgerMenu.js, car-reviews/src/components/MainPage/searchbar.js, car-reviews/yarn.lock
- react-burger-menu dependency added to package.json
- hamburgerMenu component created/styled
- imported hamburgerMenu to searchbar.js for conditional rendering
Tested in localhost on my machine using the heroku backend for login. When logged in the <HamburgerMenu/> component should render to allow for user to route to their reviews, billing, settings, etc.
=> Conditionally render a hamburger menu only if user is logged in.

car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/MainPage/searchresults.js
Changed cards displaying for search and took data from data file. 
Tested locally
=>  Setup data coming from data file to populate reviews

car-reviews/src/components/UserPage/leftnavbar.css, car-reviews/src/components/UserPage/usersettings.js
The file `usersettings.js` is now complete. It has cards with forms that fully interact with the backend and allow the user to change their username, password, or email. The cards are also minimally styled.
Addition
=> Finished usersettings.js

backend/src/models/ReviewModel.js, backend/src/routers/content/popularRouter.js, backend/src/routers/content/userRouter.js, backend/src/routers/paymentRouter.js, backend/src/routers/routing_middleware/hashPassword.js, car-reviews/src/components/Modals/reviewmodal.js
Wire backend to populate featured reviews on landing page
=> Connect backend

car-reviews/package.json, car-reviews/src/components/MainPage/searchbar.js, car-reviews/yarn.lock
working version of dropdown, where selections are stored on state.
=> committing for Andrew and Jonathan to clone

backend/src/routers/authRouter.js, backend/src/routers/content/userRouter.js, car-reviews/src/components/MainPage/loginRegister.js, car-reviews/src/components/UserPage/usersettings.js
Added Reactstrap alerts on success and failure of credential related requests. Also fixed an issue when changing credentials.
JWT was not being re-saved when credentials were modified, it is now (usersettings.js)
=> Added alerts to all credentialed requests

car-reviews/src/components/Modals/myReviewsModal.js, car-reviews/src/components/Modals/newreview.js, car-reviews/src/components/UserPage/reviewlist.js
- A users created reviews display on page with all the relevant car info.
- Decided to pass state down as props from reviewlist.js to newReviewModal and myReviewsModal as needed.
Some of the review fields on the displayed card were previously showing up as undefined.
Testing on localhost:3001 server.
=> Reviews display with relevant car info on My Reviews page

backend/src/routers/authRouter.js, car-reviews/src/App.js, car-reviews/src/components/MainPage/MainPage.js, car-reviews/src/components/MainPage/loginRegister.js, car-reviews/src/components/MainPage/maincontent.js, car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/MainPage/searchresults.js, car-reviews/src/components/Modals/reviewmodal.js, car-reviews/src/components/UserPage/checkout.js, car-reviews/src/redux/reducers/rootReducer.js
Changed `isLoggedIn` to reside in the `MainPage.js` component now. It will auto check for the presence of a JWT, and will set the user to logged in if there is a valid JWT on localstorage.
=> Changed the isLoggedIn flag so that Redux is no longer needed

backend/src/routers/authRouter.js, car-reviews/src/App.js, car-reviews/src/components/MainPage/MainPage.js, car-reviews/src/components/MainPage/loginRegister.js, car-reviews/src/components/MainPage/maincontent.js, car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/MainPage/searchresults.js, car-reviews/src/components/Modals/reviewmodal.js, car-reviews/src/components/UserPage/checkout.js, car-reviews/src/redux/reducers/rootReducer.js
Reverts Lambda-School-Labs/CS10-car-reviews#62
=> Revert "Changed the isLoggedIn flag so that Redux is no longer needed"

backend/src/routers/authRouter.js, car-reviews/package.json, car-reviews/src/components/MainPage/MainPage.js, car-reviews/src/components/MainPage/hamburgerMenu.js, car-reviews/src/components/MainPage/loginRegister.js, car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/MainPage/searchresults.js, car-reviews/src/components/UserPage/header.js, car-reviews/yarn.lock
This updated did a number of things:
- Added a 1 hour expiration time to JWTs issued through `auth/register` and `auth/login`
- Added a new route handler that just verifies JWTs from the client at `/auth/verify`
- Added logic to `MainPage.js` to check the JWT status when the page first loads
*NOTE: I didn't notice Herbert's Auth component until I was almost done with this--when the time comes I will re-write all of my logic to make use of Auth.
=> JWT Verification and Expiration Working

car-reviews/package.json, car-reviews/src/components/Modals/newreview.js, car-reviews/yarn.lock
added in dropzone as well as implementing it  along with cloudinary
tested on local machine
=> added in dropzone and cloudinary

car-reviews/src/components/Modals/newreview.css, car-reviews/src/components/Modals/newreview.js, car-reviews/src/components/Modals/reviewmodal.js
- when a user uploads an image in a new review modal, it will display on the review modal.
- state of carImage
- made sure it rendered in browser
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] My code has been reviewed by at least one peer
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
=> uploaded images displaying on review modals

car-reviews/src/components/Modals/myreviewsmodal.js, car-reviews/src/components/UserPage/reviewlist.js
- Changed the way I map over data in reviewlist.js and pass down props
- Changed how data was mapped over and info displayed on card.
- Added a delete button that removes the review from array.
- Added a handleRemove() to pass down to be used w/ myreviewsmodal delete button
- Finished implementing the handleRemove()  that requests backend server
=> User can now delete a created review.

car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/MainPage/searchresults.js
The search functionality is 100% working now. The code has been cleaned up a bit, as well as a few slight modifications.
=> Search Fully Functional

car-reviews/src/components/MainPage/maincontent.js, car-reviews/src/components/Modals/myreviewsmodal.js, car-reviews/src/components/Modals/reviewmodal.js, car-reviews/src/components/UserPage/billing.css
Implemented star rating system on the rest of the pages
tested locally
=> Frontpage stars rating

backend/src/models/ReviewModel.js, backend/src/models/UserModel.js, backend/src/routers/content/userRouter.js, backend/src/routers/routing_middleware/verifyJWTMiddleware.js, car-reviews/src/components/Modals/reviewmodal.js, car-reviews/src/components/UserPage/billing.css
Got counter to work and fixed jwt error  
Tested locally
=> Throttling views branch

backend/src/models/UserModel.js, car-reviews/src/components/Modals/newreview.css, car-reviews/src/components/Modals/newreview.js
Change new review modal to dropdown options pulling from the CarQuery API, so that the values for make, model, and trim in our database will correspond to those entered in Search. Also adds reviewsViewed field to UserModel.
=> Integrate Create New Review with Search

car-reviews/src/components/Modals/reviewmodal.js, car-reviews/src/components/UserPage/checkout.js
Got it to lock out users if not paid after reviews. 
tested on local machine
=> Lockout branch

car-reviews/src/components/MainPage/loginregister.js
Fixed the double login screens on login register
tested locally
=>  Got rid of the double login field inside login-register

car-reviews/src/components/Modals/resultsmodal.js
fixes f150 not being used in imports
=> fixs issue

car-reviews/src/components/MainPage/maincontent.js, car-reviews/src/components/MainPage/mainpage.css, car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/Modals/myreviewsmodal.js, car-reviews/src/components/Modals/resultsmodal.js, car-reviews/src/components/Modals/reviewmodal.css, car-reviews/src/components/Modals/reviewmodal.js
- adds opacity to landing page background image
- makes modal styles more uniform
- changes header font color
- rendered it while I wrote it.
=> Styling polish

backend/src/routers/content/reviewsRouter.js, car-reviews/src/components/MainPage/maincontent.js, car-reviews/src/components/MainPage/mainpage.js, car-reviews/src/components/MainPage/popularcar.js, car-reviews/src/components/MainPage/searchresults.js
Link from popular cars to search results page as if user had entered a search for that car. Add popularcar.js to facilitate linking. Add functionality to serachresults.js for when the incoming data is one car. Fix bug in search router.
=> Link from popular cars to search results

backend/src/models/UserModel.js, backend/src/routers/content/userRouter.js, car-reviews/public/index.html, car-reviews/src/components/MainPage/maincontent.js, car-reviews/src/components/Modals/reviewmodal.js, car-reviews/src/components/UserPage/reviewlist.js
Reverts Lambda-School-Labs/CS10-car-reviews#104
=> Revert "Throttling views branch"

car-reviews/.gitignore, car-reviews/src/components/Modals/newreview.js
- Andrew implemented logic in the dropdowns to use new API and made change handlers setting selected values on state for make, year, model, and trim in this.state.selectedValues.
- minor changes needed in each to set values on this.state.review for POST to work properly
- .env file contains API_KEY
- .gitignore file updated
=> Newreview.js can submit a new review using the new API in dropdown select.

backend/src/models/UserModel.js, backend/src/routers/content/userRouter.js, car-reviews/src/components/MainPage/maincontent.js
fixed some issues updating count to include date. 
local copy
=> Update count based on date in views branch

backend/src/models/UserModel.js, car-reviews/src/components/MainPage/maincontent.js
Updated  timer to only pay attention to which day it is
tested locally
=>  Updated timer to only use date

backend/src/routers/content/popularRouter.js, backend/src/routers/content/reviewsRouter.js, car-reviews/src/components/MainPage/searchbar.js, car-reviews/src/components/MainPage/searchresults.js, car-reviews/src/components/Modals/resultsmodal.js, car-reviews/src/components/Modals/reviewmodal.js
- Display all reviews (per car) in search (as shown in wireframe), not just the car.
- Fix bugs: car is no longer dipslayed in popular cars if it has no reviews, and search for a car with no reviews returns nothing (redirects to landing page).
- Usernames are mapped into dropdown on search results page; however, filtering by username is buggy: You need to click search on second time toggling username and thereafter to work (but doesn't crash app).
Tested in browser
=> Display all reviews (per car) in search; Fix search and popular cars bugs; Map over usernames for filtering search results

car-reviews/src/components/UserPage/billing.css, car-reviews/src/components/UserPage/billing.js
Completed redesign and CSS of billings page
tested locally
=> Billings branch

backend/src/routers/paymentRouter.js
Fixed bug where billing payments miss a then and catch when subscription is activated
Tested on local
=>  Updated paymentrouter to include then and catch statements

car-reviews/src/components/MainPage/searchresults.js, car-reviews/src/components/Modals/resultsmodal.js
- Implement search results by rating, year, and reviewer.
- Remove owned / rented search results filtering for now.
- Remove unused styles from searchresults.js
=> Sort search results

car-reviews/src/components/UserPage/reviewlist.js, car-reviews/src/tests/App.test.js, car-reviews/src/tests/maincontent.test.js, car-reviews/src/tests/mainpage.test.js
Finished component testing on App.js, maincontent.js, mainpage.js, etc.
- Testing for rendered components that we expect to see.
- Testing what props are passed to those components. (Does behavior change when props are undefined?)
Fixed issue w/ not being able to see a created review show in myreviews.
- this.state.data.reviews was being populated with user data not reviews
- this was the reason for the this.state.data.reviews.map is not a function error we saw on Friday afternoon.
=> Continued Testing with Jest/Enzyme & minor myreviews.js bug fix

backend/src/models/CarModel.js, backend/src/routers/content/reviewsRouter.js, backend/src/tests/model_tests/car_model_tests.js, backend/src/tests/model_tests/model_tests_helper.js, backend/src/tests/model_tests/relational_test.js, backend/src/tests/model_tests/review_model_tests.js, backend/src/tests/model_tests/user_model_tests.js, backend/src/tests/routing_tests/auth_router_tests.js, backend/src/tests/routing_tests/popular_router_tests.js, backend/src/tests/routing_tests/reviews_router_tests.js, backend/src/tests/routing_tests/routing_tests_helper.js
Finished the backend testing with Mocha, Chai, and Chai-HTTP.
Fixed tests that were no longer working because the routes had been changed.
Updated previous tests and added new ones to match the final server and database structure.
Tests have all been run both locally and with the deployed DB via the yarn commands listed in the documentation.
=> Backend Testing Complete

backend/README.md, backend/src/routers/content/reviewsRouter.js, car-reviews/src/components/MainPage/popularcar.js, car-reviews/src/components/UserPage/reviewlist.js
Update backend docs with current functionality of endpoints and changes to users, cars, and reviews models.
=> Update Backend Docs, minor non-breaking edits 

backend/src/routers/content/reviewsRouter.js, backend/src/tests/model_tests/review_model_tests.js, backend/src/tests/routing_tests/reviews_router_tests.js
After removing trims from the application, we didn't update the tests to account for their absence. I have fixed this, as well as added test entry support on a route handler in the reviews router.
- Issue with not deleting test entries
- Accommodation of removal of trims 
=> Accommodated the removal of trims in our Mocha tests
